#!/bin/bash

cat <<EOF > vars.yml
access_key_id: ${ACCESS_KEY_ID}
secret_access_key: ${SECRET_ACCESS_KEY}
security_group: ${SECURITY_GROUP}
key_pair_name: ${KEY_PAIR_NAME}
ssh_private_key: |
${SSH_PRIVATE_KEY}
region: ${REGION}
ops_manager_bucket: ${OPS_MANAGER_BUCKET}
infrastructure_network_name: ${INFRASTRUCTURE_NETWORK_NAME}
om_trusted_certs: ${OM_TRUSTED_CERTS}
# infrastructure
infrastructure_network_name: ${INFRASTRUCTURE_NETWORK_NAME}
infrastructure_iaas_identifier_0: ${INFRASTRUCTURE_IAAS_IDENTIFIER_0}
infrastructure_network_cidr_0: ${INFRASTRUCTURE_NETWORK_CIDR_0}
infrastructure_reserved_ip_ranges_0: ${INFRASTRUCTURE_RESERVED_IP_RANGES_0}
infrastructure_dns_0: ${INFRASTRUCTURE_DNS_0}
infrastructure_gateway_0: ${INFRASTRUCTURE_GATEWAY_0}
infrastructure_availability_zones_0: ${INFRASTRUCTURE_AVAILABILITY_ZONES_0}
infrastructure_iaas_identifier_1: ${INFRASTRUCTURE_IAAS_IDENTIFIER_1}
infrastructure_network_cidr_1: ${INFRASTRUCTURE_NETWORK_CIDR_1}
infrastructure_reserved_ip_ranges_1: ${INFRASTRUCTURE_RESERVED_IP_RANGES_1}
infrastructure_dns_1: ${INFRASTRUCTURE_DNS_1}
infrastructure_gateway_1: ${INFRASTRUCTURE_GATEWAY_1}
infrastructure_availability_zones_1: ${INFRASTRUCTURE_AVAILABILITY_ZONES_1}
infrastructure_iaas_identifier_2: ${INFRASTRUCTURE_IAAS_IDENTIFIER_2}
infrastructure_network_cidr_2: ${INFRASTRUCTURE_NETWORK_CIDR_2}
infrastructure_reserved_ip_ranges_2: ${INFRASTRUCTURE_RESERVED_IP_RANGES_2}
infrastructure_dns_2: ${INFRASTRUCTURE_DNS_2}
infrastructure_gateway_2: ${INFRASTRUCTURE_GATEWAY_2}
infrastructure_availability_zones_2: ${INFRASTRUCTURE_AVAILABILITY_ZONES_2}
# deployment
deployment_network_name: ${DEPLOYMENT_NETWORK_NAME}
deployment_iaas_identifier_0: ${DEPLOYMENT_IAAS_IDENTIFIER_0}
deployment_network_cidr_0: ${DEPLOYMENT_NETWORK_CIDR_0}
deployment_reserved_ip_ranges_0: ${DEPLOYMENT_RESERVED_IP_RANGES_0}
deployment_dns_0: ${DEPLOYMENT_DNS_0}
deployment_gateway_0: ${DEPLOYMENT_GATEWAY_0}
deployment_availability_zones_0: ${DEPLOYMENT_AVAILABILITY_ZONES_0}
deployment_iaas_identifier_1: ${DEPLOYMENT_IAAS_IDENTIFIER_1}
deployment_network_cidr_1: ${DEPLOYMENT_NETWORK_CIDR_1}
deployment_reserved_ip_ranges_1: ${DEPLOYMENT_RESERVED_IP_RANGES_1}
deployment_dns_1: ${DEPLOYMENT_DNS_1}
deployment_gateway_1: ${DEPLOYMENT_GATEWAY_1}
deployment_availability_zones_1: ${DEPLOYMENT_AVAILABILITY_ZONES_1}
deployment_iaas_identifier_2: ${DEPLOYMENT_IAAS_IDENTIFIER_2}
deployment_network_cidr_2: ${DEPLOYMENT_NETWORK_CIDR_2}
deployment_reserved_ip_ranges_2: ${DEPLOYMENT_RESERVED_IP_RANGES_2}
deployment_dns_2: ${DEPLOYMENT_DNS_2}
deployment_gateway_2: ${DEPLOYMENT_GATEWAY_2}
deployment_availability_zones_2: ${DEPLOYMENT_AVAILABILITY_ZONES_2}
# services
services_network_name: ${SERVICES_NETWORK_NAME}
services_iaas_identifier_0: ${SERVICES_IAAS_IDENTIFIER_0}
services_network_cidr_0: ${SERVICES_NETWORK_CIDR_0}
services_reserved_ip_ranges_0: ${SERVICES_RESERVED_IP_RANGES_0}
services_dns_0: ${SERVICES_DNS_0}
services_gateway_0: ${SERVICES_GATEWAY_0}
services_availability_zones_0: ${SERVICES_AVAILABILITY_ZONES_0}
services_iaas_identifier_1: ${SERVICES_IAAS_IDENTIFIER_1}
services_network_cidr_1: ${SERVICES_NETWORK_CIDR_1}
services_reserved_ip_ranges_1: ${SERVICES_RESERVED_IP_RANGES_1}
services_dns_1: ${SERVICES_DNS_1}
services_gateway_1: ${SERVICES_GATEWAY_1}
services_availability_zones_1: ${SERVICES_AVAILABILITY_ZONES_1}
services_iaas_identifier_2: ${SERVICES_IAAS_IDENTIFIER_2}
services_network_cidr_2: ${SERVICES_NETWORK_CIDR_2}
services_reserved_ip_ranges_2: ${SERVICES_RESERVED_IP_RANGES_2}
services_dns_2: ${SERVICES_DNS_2}
services_gateway_2: ${SERVICES_GATEWAY_2}
services_availability_zones_2: ${SERVICES_AVAILABILITY_ZONES_2}
# vm extensions
pks_api_8443: ${PKS_API_8443}
pks_api_9021: ${PKS_API_9021}
pks_api_lb_security_group: ${PKS_API_LB_SECURITY_GROUP}
vms_security_group: ${VMS_SECURITY_GROUP}
EOF